[package]
name = "claw"
version = "0.1.0"
edition = "2021"

[dependencies]
users = "0.11"
colored = "2.1.0"
rustyline = { version = "12.0.0", features = ["derive"] }
lazy_static = "1.4.0"
term_size = "0.3.2"
